CREATE DATABASE CASESTUDYKHANH;
USE CASESTUDYKHANH;

CREATE TABLE USER(
ID INT AUTO_INCREMENT,
FULLNAME VARCHAR(50),
ADDRESS VARCHAR(500),
PHONENUMBER INT(10),
USERNAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(8) NOT NULL,
PRIMARY KEY (ID)
);

DROP TABLE STUDENT;
DROP TABLE TEACHER;
DROP TABLE MONHOC;
DROP DATABASE `STUDENT-MANAGEMENT`;