CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;
CREATE TABLE USER(
ID_USER INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100),
PASSWORD VARCHAR(8),
ADDRESS VARCHAR(1000),
PHONE VARCHAR(10) NOT NULL
);
ALTER TABLE USER ADD COLUMN ADDRESS VARCHAR(1000);
ALTER TABLE USER ADD COLUMN PHONE VARCHAR(10) NOT NULL;
CREATE TABLE CATEGORY(
ID_CATEGORY INT PRIMARY KEY	AUTO_INCREMENT,
NAME_CATEGORY VARCHAR(300)
);

CREATE TABLE PRODUCT(
ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT,
ID_CATEGORY INT,
NAME_PRODUCT VARCHAR(500) NOT NULL,
IMAGE_PRODUCT VARCHAR(10000) NOT NULL,
PRICE_PRODUCT FLOAT NOT NULL,
QUANTITY_PRODUCT INT DEFAULT '0',
DESCRIPTION_PRODUCT VARCHAR(1000),
QUANTITY  INT DEFAULT '0',
FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);

-- CẬP NHẬT LẠI VARIANT
DROP TABLE VARIANT;
CREATE TABLE VARIANT(
ID_VARIANT INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCT INT,
COLOR VARCHAR(100),
TYPE VARCHAR(100),
SIZE VARCHAR(100),
FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

DROP TABLE CART;
CREATE TABLE CART(
ID_CART INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCT INT,
ID_USER INT,
NAME_PRODUCT VARCHAR(500),
IMAGE_PRODUCT VARCHAR(10000),
PRICE_PRODUCT DOUBLE,
FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

DROP TABLE `ORDER`;
CREATE TABLE `ORDER`(
ID_ORDER INT PRIMARY KEY AUTO_INCREMENT,
ID_USER INT,
FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
);

DROP TABLE `ORDER`;
CREATE TABLE `ORDER`(
ID_ORDER INT AUTO_INCREMENT PRIMARY KEY,
ID_USER INT,
ID_PRODUCT INT,
CODE_PRODUCT VARCHAR(10),
NAME_PRODUCT VARCHAR(500),
QUATITY_PRODUCT INT,
SUB_PRICE_PRODUCT DOUBLE,
DATE_TIME VARCHAR(45) NOT NULL
);
SHOW CREATE TABLE CART;
ALTER TABLE CART DROP FOREIGN KEY ID_CART_LINE;