CREATE DATABASE `QuanLyDonDatHang`;
USE QuanLyDonDatHang;
CREATE TABLE DonDatHang(
SoDH INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TenDV VARCHAR(60) NOT NULL ,
DiaChi VARCHAR(50) ,
DienThoai VARCHAR(10) ,
NgayDat DATETIME NOT NULL,
TenHang VARCHAR(60) NOT NULL,
MoTa VARCHAR(500) 
);