CREATE DATABASE `QUAN_LY_BAN_HANG`;
USE QUAN_LY_BAN_HANG;
CREATE TABLE CUSTOMER(
CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(30) NOT NULL,
CUSTOMER_AGE INT NOT NULL
);

CREATE TABLE ORDERS(
ORDERS_ID INT AUTO_INCREMENT PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
ORDERS_DATE DATE NOT NULL,
ORDERS_TOTAL_PRICE DOUBLE DEFAULT 0,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE PRODUCT(
PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
PRODUCT_NAME VARCHAR(30),
PRODUCT_PRICE DOUBLE DEFAULT 0
);

CREATE TABLE ORDER_DETAIL(
ORDERS_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
ORDER_DETAIL_QUTITY INT,
FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS (ORDERS_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);
