CREATE DATABASE `QUAN_LY_SINH_VIEN`;
USE `QUAN_LY_SINH_VIEN`;
CREATE TABLE CLASS(
CLASSID INT PRIMARY KEY,
CLASSNAME VARCHAR(10) NOT NULL,
STARTDATE DATE,
STATUS BIT
);

DROP TABLE STUDENT ;
CREATE TABLE STUDENT(
STUDENTID INT AUTO_INCREMENT PRIMARY KEY,
STUDENTNAME VARCHAR(10) NOT NULL,
ADDRESS VARCHAR(500),
PHONE VARCHAR(10),
STATUS BIT,
CLASSID INT NOT NULL,
FOREIGN KEY(CLASSID) REFERENCES CLASS(CLASSID)
);

CREATE TABLE SUBJECT(
SUBID INT PRIMARY KEY,
SUBNAME VARCHAR(10) NOT NULL,
CREDIT VARCHAR(20) NOT NULL,
STATUS BIT
);

DROP TABLE MARK ;
CREATE TABLE MARK(
MARKID INT AUTO_INCREMENT PRIMARY KEY,
SUBID INT NOT NULL,
STUDENTID INT NOT NULL,
MARK INT,
EXAM_TIMES INT,
FOREIGN KEY(SUBID) REFERENCES SUBJECT(SUBID),
FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID)
);

INSERT INTO CLASS
VALUES (1,'A1','2008-12-20',1);
INSERT INTO CLASS
VALUES (2,'A2','2008-12-22',1);
INSERT INTO CLASS
VALUES (3,'B3',current_date,0);

INSERT INTO STUDENT(STUDENTNAME,ADDRESS,PHONE,STATUS,CLASSID)
VALUES ('HUNG','HA NOI','0912113113',1,1);
INSERT INTO STUDENT(STUDENTNAME,ADDRESS,PHONE,STATUS,CLASSID)
VALUES ('HOA','HAI PHONG',NULL,1,1);
INSERT INTO STUDENT(STUDENTNAME,ADDRESS,PHONE,STATUS,CLASSID)
VALUES ('MANH','HCM','0123123123',0,2);

INSERT INTO SUBJECT
VALUES (1,'CF',5,1),
	   (2,'C',6,1),
       (3,'HDJ',5,1),
       (4,'RDBMS',10,1);
       
INSERT INTO MARK(SUBID,STUDENTID,MARK,EXAM_TIMES)
VALUES (1,1,8,1),
	   (1,2,10,2),
       (2,1,12,1);
       
