USE QUAN_LY_SINH_VIEN;
-- Hiển thị tất cả các thông tin môn học (bảng subject) có credit lớn nhất.
SELECT SUBID, SUBNAME,MAX(CREDIT) AS MAX
FROM SUBJECT
GROUP BY SUBID
HAVING MAX(CREDIT)>=(SELECT MAX(CREDIT) FROM SUBJECT );

-- Hiển thị các thông tin môn học có điểm thi lớn nhất.
SELECT SUB.SUBID,SUB.SUBNAME,MAX(MARK) AS MAX
FROM MARK AS M
JOIN SUBJECT AS SUB
ON SUB.SUBID = M.SUBID
GROUP BY SUB.SUBID, SUB.SUBNAME
HAVING MAX(MARK)>=(SELECT MAX(MARK) FROM MARK GROUP BY SUB.SUBID);

-- Hiển thị các thông tin sinh viên và điểm trung bình của mỗi sinh viên, xếp hạng theo thứ tự điểm giảm dần
SELECT S.STUDENTID, S.STUDENTNAME, S.ADDRESS, AVG(MARK) AS DIEM_TRUNG_BINH
FROM STUDENT AS S
JOIN MARK AS M
ON M.STUDENTID = S.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME, S.ADDRESS
HAVING AVG(MARK)
ORDER BY DIEM_TRUNG_BINH DESC;